За основу ноутбука взят [этот](https://bitbucket.org/bython179/nlp/src/c8236379d0840f9b3ed22b96ac679c383f3b6e8d/14/classwork.ipynb?at=default&fileviewer=notebook-viewer%3Anbviewer).


# Вселенная scipy

В питоне это называется "scipy stack", "scientific python", "numpy/scipy universe" или много как ещё, и обычно включает в себя:

- numpy: это пакет для представления многомерных данных (то есть больших табличек) и, соответственно, совершения с ними всевозможных операций -- это ключевая штука, из которой всё последующее вырастало... И меня всегда тянет называть python+numpy другим языком программирования, чем python -- и правила там некоторые по-другому себя ведут, и подход к программированию совсем другой.
- scipy: почему-то в какой-то момент часть функций для работы с этими самыми многомерными данными оказались тут... Учитывая, что и в numpy огромная гора всего, и тут гора большая, странно, что это два разных проекта, -- но как уж есть.
- matplotlib он же pylab, он же pyplot: а вот когда у нас какие-нибудь страшные данные собраны, то самое время научиться их рисовать как-нибудь... И matplotlib умеет рисовать их многими разными способами!
- sklearn, он же scikit-learn: то, ради чего мы всё это делаем -- это сосбтвенно набор уже реализованных за нас методов машинного обучения
- pandas: пока что нам не потребуется, но это важная штука -- что-то в духе экселя (или гуглтаблиц) в питоне -- очень крутой инструмент для работы с таблицами

# numpy
Это ВСЁ про многомерные массивы.

In [3]:
import numpy

но так им пользоваться неудобно, давайте дадим модулю более короткое имя:

In [1]:
import numpy as np

Основной тип данных в numpy: array. Это многомерный массив, почти всегда из чисел.

In [14]:
a = np.array([1, 2, 3])

In [15]:
a

array([1, 2, 3])

## shape и reshape

`shape` -- это размеры массива: сколько элементов по какой оси.

In [4]:
a.shape

(3,)

Это одномерный массив из трёх элементов.

In [5]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

А это двумерный массив из двух строк и трёх столбцов.

В каком порядке размерности? Напишите питонское представление массива. Первой открывающей квадратной скобочке соответствует первая размерность. Второй -- вторая.

In [6]:
b.shape

(2, 3)

Задание: создайте в numpy вложенный массив `my_arr` формы 3, 4, 2.

`reshape` перераскладывает те же элементы массива в массив другой формы. Действие себе можно представить таким образом: мы пишем питонский массив, потом стираем все квадратные скобочки и рисуем новый набор квадратных скобочек, такой, чтобы получились нужные размеры по осям. Главное: значения при этом не шелохнулись -- где лежали, там и лежат.

Исходный массив при этом не меняется, только создаётся новый другой формы.

In [13]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.reshape((1,3,2))

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

Задание: переформируйте массив `my_arr` в любую другую возможную форму.

Иногда бывает удобно делать эксперименты с массивом просто из чисел от 0 до N; в numpy для этого специально сокращение: `np.arange`

In [2]:
c = np.array(list(range(100)))
d = np.arange(100)

In [17]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
c.reshape((2,5,2,5))

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89]],

        [[90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [5]:
c.reshape((1,1,1,100))

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
          45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
          60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
          75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]]])

Единственное ограничение на `reshape`: количество элементов в массиве не должно меняться. Т.е. произведение значений в `shape` до `reshape` должно равняться произведению значений в `shape` после `reshape`.

In [9]:
np.arange(10).reshape((3, 3))

ValueError: cannot reshape array of size 10 into shape (3,3)

# Бинарные операции

Напоминание: бинарная операция -- это операция с двумя аргументами.

Все стандартные бинарные операции делаются в `numpy` поэлементно. (Вообще-то, и унарные тоже. То есть скорее нужно перечислять исключения: операции, которые делаются не поэлементно -- и их мало).

In [11]:
c + d

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [12]:
list(c + d)

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

Ещё одна полезная кнопочка в jupyter:

`o` -- спрятать выдачу команды. (Разумеется, не в режиме редактирования)

In [13]:
c * d

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

# Приведение таблиц к одинаковой форме (broadcasting)

В некоторых случаях можно сделать бинарную операцию для таблиц, имеющих различный размер.

Например, довольно естественно же разрешить операцию между таблицей и одним числом?

In [16]:
a + 1

array([2, 3, 4])

И не так уж странна идея, что таблица из одного элемента (или список из одного элемента) ведёт себя так же, как и просто одно число:

In [17]:
a + [1]

array([2, 3, 4])

А вот какие-либо операции между таблицами просто разного размера в `numpy` запрещены. Можно было бы придумать какие-нибудь правила и разрешить операции над непохожими таблицами, но почти всегда, когда потребность такую операцию сделать возникает, в действительности оказывается, что причиной была ошибка. Так лучше тогда эту операцию и вовсе запретить:

In [18]:
np.array([1,2,3]) + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Вот из этих идей и родились

## Правила приведения

 1. приведение ведётся от самой вложенной размерности (от правого края) к самой внешней (к левому краю)
 2. если по оси размер одинаковый, всё ок
 3. если по одной из осей размер 1, он размножается столько раз, сколько в другом операнде
 4. если у другого операнда есть ещё размерности, а у нас нет, то мы добавляем себе снаружи ось размера 1
 
Всё остальное -- ошибка.

## Сложный пример:

In [19]:
a = np.arange(10).reshape((2, 1, 5))
b = np.arange(10).reshape((1, 1, 2, 5, 1))

In [20]:
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [21]:
b

array([[[[[0],
          [1],
          [2],
          [3],
          [4]],

         [[5],
          [6],
          [7],
          [8],
          [9]]]]])

Как понять, что будет результатом `a + b`?

В первую очередь, нужно понять, какой формы будет результат.

Выпишем формы двух массивов друг под другом, подравняв по правому краю:

```
    2 1 5
1 1 2 5 1
```

Теперь можно пройти справа налево и написать форму итогового массива или сказать, что есть ошибка:

```
1 1 2 5 5
```

Осталось понять, что происходит собственно с данными в том случае, когда напротив 5 стояла 1. Очень просто: соответствующая строка или столбец повторялась 5 раз.

Сейчас, так как этот пример выдуман из головы, это выглядит непонятно и трудновообразимо. Позже, когда мы столкнёмся с этой ситуацией на реальных данных, поведение предсказать окажется проще. (Но сначала узнать формальные правила для этого всё же нужно)

In [22]:
a + b

array([[[[[ 0,  1,  2,  3,  4],
          [ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8]],

         [[10, 11, 12, 13, 14],
          [11, 12, 13, 14, 15],
          [12, 13, 14, 15, 16],
          [13, 14, 15, 16, 17],
          [14, 15, 16, 17, 18]]]]])

###  Пример попроще

In [26]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [24]:
a

array([[0],
       [1],
       [2]])

In [25]:
b

array([0, 1, 2])

In [27]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Здесь понять, что происходит, совсем просто:

```
+012
0
1
2
```

нужно в этой табличке заполнить каждую ячейку суммой значений по осям

# Типы данных

`numpy` создавался ради эффективности.

И он эффективен. Он и хранит данные в памяти гораздо компактнее, чем питон, и работает гораздо быстрее. Если не применять множество сложных оптимизаций, а написать программу наиболее прямолинейным образом на `numpy`, на голом `python` и на `C`, то время исполнения программ будет соотноситься примерно так: 1:100:1.2. Т.е. `numpy` почти всегда выигрывает даже у неоптимизированной программы на `C`.

Но за эффективность приходится платить. Плата за эффективность в `numpy` состоит в том, что каждый массив содержит данные только одного и того же типа (и тип данных должен быть объявлен в момент создания массива).

In [32]:
a.dtype

dtype('int64')

int64: integer number (целое число), 64 bit wide (размером 64 бита).

Кроме int бывает uint -- unsigned integer (беззнаковое целое число).

uint64 -- это число от 0 до `2**64-1`.

In [34]:
x = np.array([255]).astype('uint8')

это числа от 0 до 2**8-1 == 255

In [35]:
x

array([255], dtype=uint8)

In [36]:
x + 1

array([0], dtype=uint8)

# Задача
Постройте матрицу
```
01234
01234
01234
01234
01234
```
не вводя её прямым текстом. Т.е. чем короче и проще, тем лучше.

In [13]:
a = np.arange(5)
b = np.array([0] * 5).reshape(5, 1)
a + b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
a.dtype

dtype('int64')